version: "3.9"

services:
  auth-app-release:
    container_name: auth_app
    build:
      context: .
      target: release
      dockerfile: Dockerfile
    env_file: ".env"
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - database
  auth-app-dev:
    container_name: auth_app_dev
    restart: unless-stopped
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    env_file: ".env"
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    volumes:
      - .:/app
    depends_on:
      - database
  database:
    image: postgres:15.1
    container_name: auth_app_db
    logging:
      driver: none
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./postgres:/var/lib/postgresql/data
