export enum ErrorCode {
  BAD_REQUEST = "BAD_REQUEST", // 400
  UNAUTHORIZED = "UNAUTHORIZED", // 401
  FORBIDDEN = "FORBIDDEN", // 403
  NOT_FOUND = "NOT_FOUND", // 404
  INTERNAL_SERVER = "INTERNAL_SERVER", // 500
}
